### ISSUE TITLE
SL2.0 - NRD - No SetConstants method

### ISSUE THREAD

**Issue by Cheaterdev** [NVIDIAGameWorks/Streamline#17]
Hi! There is no method to apply NRDConstants in the latest version.

**Comment by b4df00d** [comment]
Hi, I did struggle with that also.

I found 

			bool (*slSetConstants)(const void*, uint32_t, uint32_t);
			SL_FEATURE_FUN_IMPORT(sl::kFeatureNRD, slSetConstants);
			slSetConstants((void*)&nrdConsts, *device->slCurrentFrame, device->slViewport);

If you manage to get it working past that please give me a sign, I'm stuck with this issue https://github.com/NVIDIAGameWorks/Streamline/issues/16

**Comment by BattleAxeVR** [comment]
Hi, I seem to have gotten past that can called it myself (although I called the function stub something slightly different, for NRD use only).

https://github.com/NVIDIAGameWorks/Streamline_Sample/issues/4

But I'm thinking nobody is using NRD via SL but maybe us three.

**Comment by BattleAxeVR** [comment]
I did it slightly differently, as if I declared slSetConstants function pointer that clashes with the one that sets the default parameters that has a different signature. so I called it slSetNRDConstants

TBH this is kind of silly and confusing, I wonder if NRD integration even works at all. Have either of you gotten it to work since May?

**Comment by Cheaterdev** [comment]
Looks like it should work after last commit - function is there.

**Comment by jake-nv** [comment]
The NRD plugin and docs were extensively updated in SL v2.2 for the "beta" release of that plugin.
